site:
  name: AIOS
  site: 'https://aios.pub'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: aios.pub - 探索AI无限可能
    template: '%s | aios.pub'
  description: 'AIOS 让 AI 落地为切实可用的价值。我们维护一套持续增长的开源 AI 原生（AI-native）开发者工具链与基础设施，服务现代软件工程——一个构建真实世界、价值驱动 AI 开发者生态的开源引擎。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AIOS
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@arthelokyo'
    site: '@arthelokyo'
    cardType: summary_large_image

i18n:
  defaultLanguage: zh
  languages: [zh, en]
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
